index.html
styles.css

Improving the layout of the skills section for better visual organization
Before:
After:

Fixing skills section layout

---

tsconfig.json

[Change] tsconfig dep

---

astro.config.mjs
tsconfig.json

[Change] Config changes

---

src/components/projectCard.astro
src/components/projects.astro

[Change] Demo deleted from StockIn

---

src/components/projects.astro

[Add] StockIn demo url

---

src/components/nav.astro

Nav error updated

---

src/components/footer.astro
src/layouts/Layout.astro

Fix + Description

---

src/React/LetterGlitch.tsx
src/React/SkillsList.tsx
src/components/contact.astro
src/components/home.astro

Home section style improved

---

package-lock.json
package.json
src/React/LikeButton.tsx
src/React/SkillsList.tsx
src/components/footer.astro
src/components/home.astro
src/firebase.ts
tailwind.config.mjs
tsconfig.json

Small changes to home + Like button with Firebase

---

src/components/nav.astro

[Style] section active

---

src/components/nav.astro

Style fix 2/2

---

src/React/LikeButton.tsx

[Fix] to avoid multiple likes

---

src/layouts/Layout.astro

Deleted vercel-speedInsights + Font optimization

---

src/components/logoWall.astro

logoWall improved

---

src/components/footer.astro

[Add] Warning on copyright

---

package-lock.json
package.json

Remove: Dependencies

---

src/layouts/Layout.astro

Add(og attributes)

---

astro.config.mjs
package.json
pnpm-lock.yaml
tsconfig.json

Remove: unused dependencies

---

src/components/footer.astro

Fix(footer): alignment

---

src/components/footer.astro

Change(playlist)

---

src/components/footer.astro

Change(playlist): on repeat
